application/application/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from dbmaster.views import HomeView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', TemplateView.as_view(template_name="registration/login.html"),name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('employees/',include('employees.urls')),   
    path('attendance/',include('attendance.urls')),   
    path('salaryreports/',include('salaryreports.urls')),
    path('',include('dbmaster.urls')),  
]

application/attendance/urls.py
from django.urls import include, path
from employees.models import get_employees,get_emp_details

from attendance.views import (AttendanceCreateView, AttendanceUpdateView,
                              copy_attendance, navigate_attendance,
                              search_attendance,MonthlyReportView,get_report_data)

from . import views

app_name="attendance"
urlpatterns = [
    path('attendance-create/', AttendanceCreateView.as_view(), name = 'attendance-create'),
    path('<int:pk>/update',AttendanceUpdateView.as_view(),name='attendance-details'),
    path('nav-attendance/',views.navigate_attendance,name='nav-attendance'),
    path('search-attendance',views.search_attendance,name='search-attendance'),
    path('copy-attendance',views.copy_attendance,name='copy-attendance'),
    
    path('monthly-report',MonthlyReportView.as_view(),name='monthly-report'),
    path('attendance-data',views.get_report_data,name='attendance-data'),

        
    path('json/emps-autocomplete/',get_employees, name='emps-autocomplete'),
    path('json/emps-details/',get_emp_details, name='emps-details'),
]

application/dbmaster/urls.py
from django.urls import include, path
from . import  views
from dbmaster.views import HomeView

app_name="dbmaster"
urlpatterns = [
     path('',HomeView.as_view(),name='home'),
         
]

application/attendance/models.py
import datetime
from datetime import date, timedelta
from decimal import Decimal
from dbmaster.models import (WorkingHour,HolidayDetail)
from django.db import models
from django.db.models import Q
from employees.models import Employee

class Attendance(models.Model):    
    year=models.CharField(max_length=4)
    month=models.CharField(max_length=2)
class AttendanceDetail(models.Model):
    employee_name=models.CharField('EmpName',max_length=100)  
    days=models.DecimalField('Total Hours',max_digits=3,decimal_places=1,null=True,default=0)
    leaves=models.DecimalField('Leaves',max_digits=3,decimal_places=1,null=True,default=0)
    employee_no=models.ForeignKey(Employee,on_delete=models.PROTECT)
    attendance=models.ForeignKey('Attendance',on_delete=models.PROTECT)
  


def get_all_date(from_date,to_date):
    date_array=[]
    from_date=datetime.datetime.strptime(str(from_date),'%Y-%m-%d')
    to_date =datetime.datetime.strptime(str(to_date),'%Y-%m-%d')
    ''' Create date'''
    start_date = date(from_date.year,from_date.month,from_date.day)
    end_date = date(to_date.year,to_date.month,to_date.day)
    delta = end_date - start_date
    for i in range(delta.days + 1):
        dates = start_date + timedelta(days=i)
        date_array.append(dates)
    return date_array

def get_working_dates(from_date,to_date,emp_id):
    emp_details=Employee.objects.filter(employee_no=emp_id).values('work_hours_code')
    all_dates =get_all_date(from_date,to_date)
    holidays =get_public_holidays(from_date,to_date)
    date_hours=get_date_hours(all_dates,holidays,emp_details[0]['work_hours_code'])
    datestatus=get_date_status(date_hours)
    return datestatus
def get_date_hours(all_dates,holiday_dates,workhrscode):
    dateshrs={}
    for dat in all_dates:
        dateshrs[dat]=Decimal(WorkingHour.objects.filter(id=workhrscode).values()[0][str.lower(dat.strftime('%a'))])
    for dat in holiday_dates:
        dateshrs[dat]=0
    return dateshrs
def get_date_status(datehrs):
    datearr={}
    datewklist=[]
    daterdlist=[]
    for key ,hours in datehrs.items():
        if hours and int(hours) > 0:
           datewklist.append(key)
           datearr['workingdays']=datewklist
        else:
           daterdlist.append(key)
           datearr['restingdays']=daterdlist
    return datearr

def get_public_holidays(from_date,to_date):
    pholiday_array=[]
    queryset=HolidayDetail.objects.filter(holiday_date__range=[from_date,to_date]).order_by('holiday_date')
    for holiday in queryset:
        pholiday_array.append(holiday.holiday_date)
    return pholiday_array
  

application/attendance/forms.py
from django import forms
import  datetime
from attendance.models import Attendance, AttendanceDetail
from employees.models import Employee
from django.forms.models import inlineformset_factory
from dbmaster.models import SalaryPeriod

class AttendanceCreateForm(forms.ModelForm):  
      class Meta:
            model = Attendance
            fields=['year','month']
      def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)           
            self.fields['month'].initial = datetime.datetime.now().month
      id=forms.CharField(widget=forms.TextInput(attrs={
            'id':'id',
            'value':'',
            'size':'6',
            'autocomplete':'off',
      }),required=False)
      year=forms.ChoiceField(
          choices=SalaryPeriod.get_years,
         initial=0)
      month=forms.ChoiceField(
       choices=SalaryPeriod.get_months,
       required=False)
      
class  AttendanceUpdateForm(forms.ModelForm):
      class Meta:
            model = Attendance
            fields=['id','year','month']
      id=forms.CharField(widget=forms.TextInput(attrs={
      'id':'attn_id',
      'value':'',
      'autocomplete':'off',
      }),required=False)

      year=forms.ChoiceField(
          choices=SalaryPeriod.get_years,
         initial=0)

      month=forms.ChoiceField(
       choices=SalaryPeriod.get_months,
       required=False)
class AttendanceDetailsForm(forms.ModelForm):
      class Meta:
            model = AttendanceDetail
            fields=['employee_no','employee_name','days','leaves']
      employee_no=forms.ModelChoiceField(
                  queryset = Employee.objects.all(),
                  widget=forms.TextInput(attrs={
                  'size':6,
            'style':'text-align:center;',
            'class':'unique row-nav form-control-small select2'
      }))
      employee_name=forms.CharField(widget=forms.TextInput(attrs={
            'readonly':'readonly',
      }))     
      days=forms.DecimalField(widget=forms.TextInput(attrs={
            'class':'text-right row-nav',
            'onclick': 'this.select();',
             'size':6,             
            'pattern':'(?:1[0-9]|[0-9])(?:1[0-9]|[0-9])(?:\.[0-9])?',
            'autocomplete':'off'
      }),required=False)
      leaves=forms.DecimalField(widget=forms.TextInput(attrs={
            'class':'text-right row-nav',
            'onclick': 'this.select();',
             'size':6,             
            # 'pattern':'(?:1[0-9]|[0-9])(?:\.[0-9])?',
            'autocomplete':'off'
      }),required=False)

AttendanceFormset=inlineformset_factory(Attendance,AttendanceDetail,extra=10,form=AttendanceDetailsForm)


class MonthlyReportForm(forms.Form):
      year=forms.ChoiceField(
          choices=SalaryPeriod.get_years,
         initial=0)

      month=forms.ChoiceField(
       choices=SalaryPeriod.get_months,
       )
      

application/attendance/views.py
from django.contrib import messages
import  datetime

from django.utils.dateparse import parse_date
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.db.models import Q
from django.contrib.messages.views import SuccessMessageMixin
from dateutil.relativedelta import relativedelta

from django.forms.models import inlineformset_factory

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render,redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView,View

from attendance.forms import (AttendanceCreateForm, AttendanceDetailsForm,
                              AttendanceUpdateForm,AttendanceFormset,MonthlyReportForm)
from attendance.models import Attendance, AttendanceDetail
from attendance.get_report_data import  get_monthly_report
from dbmaster.models import  get_post_array, navigate_model,check_open_month,period_dates
from employees.models import Employee


class AttendanceCreateView(LoginRequiredMixin,CreateView):
      form_class=AttendanceCreateForm
      permission_required='attendance.add_attendance'
      template_name='attendance.html'
      attendance_details_form_set= AttendanceFormset
      def get_context_data(self,**kwargs):
            data = super().get_context_data(**kwargs)
            if self.request.method == 'POST':
                data["details"] = self.attendance_details_form_set(self.request.POST)
            else:
                data["details"] = self.attendance_details_form_set()
            return data

      def form_valid(self, form):
            context = self.get_context_data()
            details = context["details"]
            if check_open_month(self.request.POST['year'],self.request.POST['month']):
                id=check_duplicates('',self.request.POST['year'],self.request.POST['month'])
                if id:
                    messages.success(self.request, 'Duplicates not allowed')
                    return HttpResponseRedirect(reverse("attendance:attendance-details",kwargs={'pk':id}))
                else:
                    if details.is_valid():
                        self.object = form.save()
                        details.instance = self.object
                        details.save()
                        messages.success(self.request, 'Attendance Added')
                    else:
                        messages.warning(self.request, "Attendance Couldn't be added")
                    return super().form_valid(form)
            else:
                    messages.warning(self.request, 'No Add Period Locked')
                    return self.render_to_response(self.get_context_data(form=form))


      def get_success_url(self):
             return reverse("attendance:attendance-details",kwargs={'pk':self.object.id})


class AttendanceUpdateView(LoginRequiredMixin,UpdateView):
      model = Attendance
      form_class=AttendanceUpdateForm
      template_name='attendance_details.html'
      attendance_details_form_set= AttendanceFormset
      def get_context_data(self,**kwargs):
                data = super().get_context_data(**kwargs)
                if self.request.method == 'POST':
                       data["details"] = self.attendance_details_form_set(self.request.POST,instance=self.object)
                else:
                        data["details"] = self.attendance_details_form_set(instance=self.object)
                return data
      def form_valid(self, form):
                context = self.get_context_data()
                details = context["details"]
                if  check_open_month(self.request.POST['year'],self.request.POST['month']):
                    id=check_duplicates(self.request.POST['id'],self.request.POST['year'],self.request.POST['month'])
                    if id:
                        messages.success(self.request, 'Duplicates not allowed')
                        return HttpResponseRedirect(reverse("attendance:attendance-details",kwargs={'pk':id}))
                    else:
                        self.object = form.save()
                        if details.is_valid():
                            messages.success(self.request, 'Well Done!  Attendance Updated')
                            details.instance = self.object
                            details.save()
                        else:
                            messages.warning(self.request, "Ooh No! Attendance Couldn't be updated")
                        return super().form_valid(form)
                else:
                    messages.warning(self.request, 'No Update Period Locked')
                    return self.render_to_response(self.get_context_data(form=form))

      def get_success_url(self):
             return reverse("attendance:attendance-details",kwargs={'pk':self.kwargs['pk']})


def navigate_attendance(request):
    if request.POST:
              nav_btn_data=get_post_array(request.POST.items(),dict())
              id=navigate_model(nav_btn_data,Attendance)
              if id:
                    return HttpResponseRedirect(reverse("attendance:attendance-details",kwargs={'pk':id}))
              else:
                     return HttpResponseRedirect(reverse("attendance:attendance-create"))


def search_attendance(request):
    if request.POST:
              array=get_post_array(request.POST.items(),dict())
              if array['id']:
                    querset=Attendance.objects.filter(id=array['id']).values('id')
                    if querset:
                        return HttpResponseRedirect(reverse("attendance:attendance-details",kwargs={'pk':querset[0]['id']}))
                    else:
                        messages.warning(request,"Serial Number not Found")
                        return HttpResponseRedirect(reverse("attendance:attendance-create"))
              elif array['id']=='' and array['year'] and array['month']:
                   querset=Attendance.objects.filter(year=array['year'],month=array['month']).values('id')
                   if querset:
                         return HttpResponseRedirect(reverse("attendance:attendance-details",kwargs={'pk':querset[0]['id']}))
                   else:
                        messages.warning(request,"Attendance not Found")
                        return HttpResponseRedirect(reverse("attendance:attendance-create"))
              else:
                        messages.warning(request,"No search Criteria Given")
                        return HttpResponseRedirect(reverse("attendance:attendance-create"))

def check_duplicates(id,year,month):
    if id :
       querset=Attendance.objects.exclude(id=id).filter(year=year,month=month).values('id')
    else:
       querset=Attendance.objects.filter(year=year,month=month).values('id')
    if querset:
        return querset[0]['id']
    else:
        return False



def copy_attendance(request):
    initial={}
    if request.POST:
            array=get_post_array(request.POST.items(),dict())
            if array['id']:
                initial['month']=(int(array['month']) +1,1)[int(array['month']) +1==13]           
                initial['year']=(array['year'],int(array['year']) + 1)[int(array['month']) +1==13]    
                form=AttendanceCreateForm(initial=initial)
                data=[{
                    'employee_name':row.employee_name,               
                    'employee_no':row.employee_no,
                    'days':''
                } for row in AttendanceDetail.objects.filter(attendance=array['id']).all()]
                formset=AttendanceFormset(initial=data)
            return render(request,'attendance.html' ,{'form':form,'details':formset})



class MonthlyReportView(LoginRequiredMixin,ListView):
         form_class=MonthlyReportForm
         template_name = 'monthly_report.html'      
         def get(self, request,**kwargs):
               form = self.form_class(initial=self.get_initial())
               return render(request,self.template_name, {'form': form})
         def get_initial(self):
               initial_base={}
               initial_base['year']=(datetime.datetime.now().year ,self.request.GET.get('year'))[self.request.GET.get('year') is not None]
               initial_base['month']=(datetime.datetime.now().month,self.request.GET.get('month')) [self.request.GET.get('month') is not None]                    
               return initial_base



def get_report_data(request):
    form = MonthlyReportForm()
    template_name = 'monthly_report.html'
    context = {"form": form}
    if request.POST:
        initial_base={}
        initial_base['year']=request.POST.get('year')
        initial_base['month']=request.POST.get('month')        
        form =MonthlyReportForm(initial=initial_base)
        year = request.POST.get('year')
        month = request.POST.get('month')
        period=period_dates(year,month)    
        if year and month:
                queryset =Employee.objects.filter(Q(date_of_leaving__isnull=True)|Q(date_of_leaving__range=[period['from_date'],period['to_date']])|Q(date_of_leaving__gte=period['from_date']),date_of_joining__lte=period['to_date']).all().order_by('employee_no')
        else:
                queryset =Employee.objects.none()
        context = {"form": form}
        if queryset:
            data=get_monthly_report(queryset,year,month)
            context['rows']=data['rows']
            context['totals']=data['totals']
    return render(request, template_name, context)

application/attendance/templates/attendance.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
<script>
    $(document).ready(function(){
        
        $("button[name='nav-button']").click(function() {
            $('#attendanceForm').attr('action',"{% url 'attendance:nav-attendance'%}").submit();
        });
        $("button[name='search']").click(function() {
            $('#attendanceForm').attr('action',"{% url 'attendance:search-attendance'%}").submit();
        });
            
        $('#detailTable .row-nav').keydown(function(e) {
        switch (e.which) {
        //Enter Key
              case 13:
                $(this).closest('tr').next().children().eq($(this).closest('td').index()).find('input').focus().select(); break;
    
        //arrow down
              case 40:
                $(this).closest('tr').next().children().eq($(this).closest('td').index()).find('input').focus(); break;
            //arrow up
              case 38:
                $(this).closest('tr').prev().children().eq($(this).closest('td').index()).find('input').focus(); break;
            }
        });
    
        $('input').focus(function() {
            $($(this)).closest('tr').find('input').addClass('row-highlight');
        }).blur(function() {
            $($(this)).closest('tr').find('input').removeClass('row-highlight');
        });
    
         $('#attendanceForm').keydown(function(e) {
        //on enter submit the form
        if (e.which == 13) {
            e.preventDefault();
            return false;
        }
        });
    
    });
    function getEmpdetials(rowId)
    {
        $("#id_attendancedetail_set-"+rowId+"-employee_no").autocomplete({
        source: "{% url 'attendance:emps-autocomplete' %}",
        autoFocus: true,
        select: function(event, ui) {
            $(event.target).val(ui.item.value);
            $.getJSON("{% url 'attendance:emps-details' %}?code=" + ui.item.value, null,
            function(data){
                $('#id_attendancedetail_set-'+rowId+'-employee_name').val(data.employee_name);
                $('#id_attendancedetail_set-'+rowId+'-days').val(0);
                });
            return false;
            }
        });
    }
   
    </script>
<style>
    
    #detailTable th {
      background: #eceff2 !important;
      position: sticky;
      top: 0;
      color: black;
      box-shadow: 0 2px 2px -1px rgba(0, 0, 0, 0.4);      
    }
    #detailTable input,select {border: 0 !important; width: 100% !important; border-radius: 0 !important; background-color: #fff;}
    #tb-master input,select {border: 0 !important; width: 100% !important; border-radius: 0 !important; background-color: #fff;}
</style>
<div class="pd-50 pd-sm-60 bg-white-6 wd-xl-100p" style="margin: 0 auto;">
    <form action="{% url 'attendance:attendance-create' %}" method="POST" id="attendanceForm">
        {% csrf_token %}
        {{form.media}}
        {{ details.management_form }}
        <div class="row row-sm">
            <div class="col-lg-4 mg-t-20 mg-lg-t-0 text-left">
                <div class="btn-group" role="group" aria-label="Basic example">
                    <button type="submit" class="btn btn" name="nav-button" value="first" formnovalidate>
                        <span class="fa fa-fast-backward"></span></button>
                    <button type="submit" class="btn btn" accesskey="p" name="nav-button" value="backward" formnovalidate>
                        <span class="fa fa-step-backward"></span></button>
                </div>
              </div><!-- col-2 -->
              <div class="col-lg-4 mg-t-20 mg-lg-t-0 text-center">
                <h5 class="">Attendance Work Sheet</h5>              
              </div>
              <div class="col-lg-4 mg-t-20 mg-lg-t-0 text-right">
                <div class="btn-group" role="group" aria-label="Basic example">
                    <button type="submit" class="btn btn" accesskey="n" name="nav-button" value="forward" formnovalidate>
                        <span class="fa fa-step-forward"></span></button>
                    <button type="submit" class="btn btn" name="nav-button" value="last" formnovalidate>
                        <span class="fa fa-fast-forward"></span></button>
                </div>
              </div>

        </div>
        </br>
        <div class="row row-xs align-items-center mg-b-20">
            <table class="table table-striped table-bordered table-hover table-sm" id="tb-master">
                <tr class="info">
                    <th class="text-center">ID</th>
                    <th class="text-center">Year</th>
                    <th class="text-center">Month</th>                 
                </tr>
                <tr>
                    <td>{{form.id}}</td>
                    <td>{{form.year}}</td>                
                    <td>{{form.month}}</td>
                </tr>
            <tr class="info">
                <td colspan="3">&nbsp;</td>
            </tr>
            </table>
    </div><!-- row -->
    <div class="row row-xs align-items-center mg-b-20 table-responsive" style="width:930px;overflow-y:scroll;" id="detaildiv">
        <table class="table table-striped table-bordered table-hover table-sm" style="margin-bottom:-20px !important" id="detailTable">
            <thead>
            <tr class="info">
                <th class="text-center">Si</th>
                <th class="text-center">Emp No</th>
                <th class="text-center">Employee Name</th>  
                <th class="text-center">Days</th>
                <th class="text-center">Leaves</th>
                <th class="text-center">Delete</br>/Clear</th>
            </tr>
            </thead>
            <tbody>
                {% for attendance in details %}
                <tr>
                 <td>{{ forloop.counter }}</td>
                {% for field in attendance.visible_fields %}
                <td {% if field.field.widget.input_type == 'hidden' %}style="display:none" {%endif%} >{{field}}</td>
                {% endfor %}
                <script type="text/javascript">
                    $(function(){getEmpdetials("{{ forloop.counter0 }}"); });
                </script>
                </tr>
                {% endfor %}
               </tbody>
              </table>
    </div> 
</br>
    <input  class="btn btn-light pd-x-30 mg-r-5"  type="submit" value="Search"/>
    <input  class="btn btn-primary pd-x-30 mg-r-5"  type="submit" value="Add"/>
    <a href="{% url 'attendance:attendance-create' %}"  class="btn btn-danger pd-x-30">Cancel</a>
    </form>
   

</div>


{% endblock %}

application/attendance/templates/attendance_details.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
<script>
    $(document).ready(function(){
        $("button[name='nav-button']").click(function() {
            $('#attendanceForm').attr('action',"{% url 'attendance:nav-attendance'%}").submit();
        });
        $("button[name='copy']").click(function() {
            $('#attendanceForm').attr('action',"{% url 'attendance:copy-attendance'%}").submit();
        });
           
        $('#detailTable .row-nav').keydown(function(e) {
        switch (e.which) {
        //Enter Key
              case 13:
                $(this).closest('tr').next().children().eq($(this).closest('td').index()).find('input').focus().select(); break;
    
        //arrow down
              case 40:
                $(this).closest('tr').next().children().eq($(this).closest('td').index()).find('input').focus(); break;
            //arrow up
              case 38:
                $(this).closest('tr').prev().children().eq($(this).closest('td').index()).find('input').focus(); break;
            }
        });
    
        $('input').focus(function() {
            $($(this)).closest('tr').find('input').addClass('row-highlight');
        }).blur(function() {
            $($(this)).closest('tr').find('input').removeClass('row-highlight');
        });
    
         $('#attendanceForm').keydown(function(e) {
        //on enter submit the form
        if (e.which == 13) {
            e.preventDefault();
            return false;
        }
        });
    
    });
    function getEmpdetials(rowId)
    {
        $("#id_attendancedetail_set-"+rowId+"-employee_no").autocomplete({
        source: "{% url 'attendance:emps-autocomplete' %}",
        autoFocus: true,
        select: function(event, ui) {
            $(event.target).val(ui.item.value);
            $.getJSON("{% url 'attendance:emps-details' %}?code=" + ui.item.value, null,
            function(data){
                $('#id_attendancedetail_set-'+rowId+'-employee_name').val(data.employee_name);
                $('#id_attendancedetail_set-'+rowId+'-days').val(0);
                });
            return false;
            }
        });
    }
    </script>
<style>
    
    #detailTable th {
      background: #eceff2 !important;
      position: sticky;
      top: 0;
      color: black;
      box-shadow: 0 2px 2px -1px rgba(0, 0, 0, 0.4);      
    }
    #detailTable input,select {border: 0 !important; width: 100% !important; border-radius: 0 !important; background-color: #fff;}
    #tb-master input,select {border: 0 !important; width: 100% !important; border-radius: 0 !important; background-color: #fff;}
</style>
<div class="pd-50 pd-sm-60 bg-white-6 wd-xl-100p" style="margin: 0 auto;">
    <form action="" method="POST" id="attendanceForm" class="deptsForm">
        {% csrf_token %}
        {{form.media}}
        {{ details.management_form }}
        {{ details.non_form_errors }}
        <div class="row row-sm">
            <div class="col-lg-4 mg-t-20 mg-lg-t-0 text-left">
                <div class="btn-group" role="group" aria-label="Basic example">
                    <button type="submit" class="btn btn" name="nav-button" value="first" formnovalidate>
                        <span class="fa fa-fast-backward"></span></button>
                    <button type="submit" class="btn btn" accesskey="p" name="nav-button" value="backward" formnovalidate>
                        <span class="fa fa-step-backward"></span></button>
                </div>
              </div><!-- col-2 -->
              <div class="col-lg-4 mg-t-20 mg-lg-t-0 text-center">
                <h5 class="">Attendance Work Sheet</h5>              
              </div>
              <div class="col-lg-4 mg-t-20 mg-lg-t-0 text-right">
                <div class="btn-group" role="group" aria-label="Basic example">
                    <button type="submit" class="btn btn" accesskey="n" name="nav-button" value="forward" formnovalidate>
                        <span class="fa fa-step-forward"></span></button>
                    <button type="submit" class="btn btn" name="nav-button" value="last" formnovalidate>
                        <span class="fa fa-fast-forward"></span></button>
                </div>
              </div>

        </div>
        </br>
        <div class="row row-xs align-items-center mg-b-20" >
            <table class="table table-striped table-bordered table-hover table-sm" id="tb-master">
                <tr class="info">
                    <th class="text-center">ID</th>
                    <th class="text-center">Year</th>
                    <th class="text-center">Month</th>                 
                </tr>
                <tr>
                    <td>{{form.id}}</td>
                    <td>{{form.year}}</td>                
                    <td>{{form.month}}</td>
                </tr>
            <tr class="info">
                <td colspan="3">&nbsp;</td>
            </tr>
            </table>
    </div><!-- row -->
    <div class="row row-xs align-items-center mg-b-20 table-responsive" style="width:940px;overflow-y:scroll;" id="detaildiv">
        <table class="table table-striped table-bordered table-hover table-sm" style="margin-bottom:-20px !important" id="detailTable">
            <thead>
            <tr class="info">
                <th class="text-center">Si</th>
                <th class="text-center">Emp No</th>
                <th class="text-center">Employee Name</th>  
                <th class="text-center">Days</th>
                <th class="text-center">Leaves</th>
                <th class="text-center">Delete</br>/Clear</th>
            </tr>
            </thead>
            <tbody>
                {% for attendance in details %}
                <tr>
                 <td>{{ forloop.counter }}</td>
                {% for field in attendance %}              
                <td {% if field.field.widget.input_type == 'hidden' %}style="display:none" {%endif%} >{{field}}</td>
                {% endfor %}
                <script type="text/javascript">
                    $(function(){getEmpdetials("{{ forloop.counter0 }}"); });
                </script>
                </tr>
                {% endfor %}
               </tbody>
              </table>
    </div> 
</br>
    <input  class="btn btn-primary pd-x-30 mg-r-5"  type="submit" value="update"/>
    <button type="submit" class="btn btn-warning btn-form" onclick="notrequired('attendanceForm')" name="copy">Copy</button>
    <a href="{% url 'attendance:attendance-create' %}"  class="btn btn-danger pd-x-30">Cancel</a>
    </form>
   

</div>



{% endblock %}