application/application/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from dbmaster.views import HomeView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', TemplateView.as_view(template_name="registration/login.html"),name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('employees/',include('employees.urls')),   
    path('attendance/',include('attendance.urls')),   
    path('salaryreports/',include('salaryreports.urls')),
    path('',include('dbmaster.urls')),  
]

application/dbmaster/urls.py
from django.urls import include, path
from . import  views
from dbmaster.views import HomeView

app_name="dbmaster"
urlpatterns = [
     path('',HomeView.as_view(),name='home'),
         
]

application/salaryreports/urls.py
from django.urls import include, path
from . import views
from salaryreports.views import  MonthlyReportView,StatutoryReportView,ItaxReportView,EmployeePaySlipView,get_print_preview
app_name="salaryreports"
urlpatterns = [
    path('monthly-salary-report',MonthlyReportView.as_view(),name='monthly-salary-report'),
    path('nssf-nhif-report',StatutoryReportView.as_view(),name='nssf-nhif-report'),
    path('itax-report',ItaxReportView.as_view(),name="itax-report"),       
    path('payslip-print',EmployeePaySlipView.as_view(),name="payslip-print"),
    path('payslip-print-preview',get_print_preview,name="payslip-print-preview"),
    
]

application/salaryreports/models/statutory_report_model.py
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.views.generic.list import ListView
from salaryreports.forms import StatutoryReportForm
from salaryreports.models import get_pay_calculation
from collections import OrderedDict
from multiprocessing import Pool, cpu_count,Manager
import functools
from decimal import Decimal

from employees.models import Employee
from dbmaster.models import SalaryPeriod,Company,period_dates



def get_statutory_report(year,month,permanent,casual):
    nhif_data = OrderedDict()
    nssf_data = OrderedDict()
    nhif_total = 0
    total_income = 0
    nssf_total_member = 0
    nssf_total_employer = 0
    casual_employees=0
    permanent_employees=0
    permanent_salary_data={}
    casuals_salary_data={}
    for employee in permanent:
        data=get_statutory_mult_data(year,month,employee)
        if data['nssf_data']['member_nssf_amount']>0:
            permanent_employees+=1
            nssf_data[str(data['nssf_data']['employee_no'])+'p']=data['nssf_data']
            permanent_salary_data.update({data['nssf_data']['employee_no']:data['permanent_salary_data']})
            nssf_total_member += Decimal(data['nssf_data']['member_nssf_amount'])
            nssf_total_employer += Decimal(data['nssf_data']['employer_nssf_amount'])
            total_income += Decimal(data['nssf_data']['gross_salary'])
            #nhif-data
            nhif_data[str(data['nhif_data']['employee_no'])+'p'] =data['nhif_data']
            nhif_total += Decimal(data['nhif_data']['nhif_amount'])
    return_arry={
        'nhif_data':nhif_data,
        'nssf_data':nssf_data,
        'nhif_total':nhif_total,
        'total_income':total_income,
        'nssf_total_member':nssf_total_member,
        'nssf_total_employer':nssf_total_employer,
        'permanent_employees':permanent_employees,
        'casual_employees':casual_employees,
        'total_no_of_employee':permanent_employees+casual_employees,
        'permanent_salary_data':permanent_salary_data,
        'casual_salary_data':casuals_salary_data
        }

    return return_arry

def get_statutory_mult_data(year, month,employee):
            return_data = get_pay_calculation(year, month, employee)    
            nhif_data = {
                    'employee_no':return_data['employee_no'],                   
                    'first_name':return_data['first_name'],
                    'other_name':return_data['other_name'],
                    'national_id':employee.national_id,
                    'nhif_no':employee.nhif_no,
                    'nhif_amount':Decimal(return_data['nhif_amount'])
            }
            nssf_data= {
                    'employee_no':return_data['employee_no'],                   
                    'first_name':return_data['first_name'],
                    'other_name':return_data['other_name'],
                    'national_id':employee.national_id,
                    'pin_no':employee.pin_no,
                    'nssf_no':employee.nssf_no,
                    'member_nssf_amount':Decimal(return_data['nssf_amount']),
                    'employer_nssf_amount':round(Decimal(return_data['nssf_amount'])),
                    'gross_salary':Decimal(return_data['gross_salary']),
                    'total_contribution':Decimal(return_data['nssf_amount']) + Decimal(return_data['nssf_amount']) * Decimal(return_data['employee_contribution']),
                    'paye_amount':Decimal(return_data['paye_amount']),
                    'nita_deduction':0
            }
            return_data['nssf_amount']=nssf_data['member_nssf_amount']
            return_data['paye_amount']=nssf_data['paye_amount']
            return  {'nssf_data':nssf_data,'nhif_data':nhif_data,'permanent_salary_data':return_data}

application/salaryreports/forms.py
from django import forms
import  datetime
from django.forms.models import inlineformset_factory
from dbmaster.models import SalaryPeriod


class MonthlyReportForm(forms.Form):
    year=forms.ChoiceField(
        choices=SalaryPeriod.get_years,
        initial=0)
    
    month=forms.ChoiceField(
    choices=SalaryPeriod.get_months,
    required=False)
class StatutoryReportForm(forms.Form):
    year = forms.ChoiceField(choices=(SalaryPeriod.get_years))
    month = forms.ChoiceField(choices=(SalaryPeriod.get_months))

class ItaxReportForm(forms.Form):
    year = forms.ChoiceField(choices=(SalaryPeriod.get_years))
    month = forms.ChoiceField(choices=(SalaryPeriod.get_months))
    
class PayslipForm(forms.Form):
    year=forms.ChoiceField(widget=forms.Select(attrs={'class':'form-control'}),
        choices=SalaryPeriod.get_years,
        initial=0)

    month=forms.ChoiceField(widget=forms.Select(attrs={'class':'form-control'}),
    choices=SalaryPeriod.get_months,
    required=False)
    
   
   

application/salaryreports/views.py
import datetime

from dbmaster.models import (SalaryPeriod, check_open_month,
                             get_post_array, period_dates)
from django.contrib import messages
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.db.models import Q
from decimal import Decimal
from django.shortcuts import render
from django.views.generic.list import ListView
from employees.models import Employee
from dbmaster.models import Company,round_half_up
from salaryreports.forms import MonthlyReportForm,StatutoryReportForm,ItaxReportForm,PayslipForm
from salaryreports.models import (get_pay_calculation,get_payment_report,get_statutory_report,save_salary,SavedSalary)


class MonthlyReportView(LoginRequiredMixin,ListView):
      form_class=MonthlyReportForm     
      template_name ='monthly_salary_report.html'
      def get_initial(self):
            initial_base={}
            initial_base['year']=(datetime.datetime.now().year ,self.request.GET.get('year'))[self.request.GET.get('year') is not None]
            initial_base['month']=(datetime.datetime.now().month,self.request.GET.get('month')) [self.request.GET.get('month') is not None]          
            return initial_base
      def get_queryset(self):
            year = self.request.GET.get('year')
            month = self.request.GET.get('month')                   
            if year and month:
                period=period_dates(year,month) 
                queryset =Employee.objects.filter(Q(date_of_leaving__isnull=True)|Q(date_of_leaving__range=[period['from_date'],period['to_date']])|Q(date_of_leaving__gte=period['from_date']),date_of_joining__lte=period['to_date']).all()
            else:
                queryset =Employee.objects.none()
            form = self.form_class(initial=self.get_initial())
            data_array={}
            salary_data={}
            salary_data['form']=form
            if self.request.GET.get('close'):
                employees_to_close(get_post_array(self.request.GET.items(),dict),len(queryset),year,month)
            if self.request.GET.get('update'):
               recalculate_salary(queryset,year,month)
            if queryset:
               return_data=get_payment_report(queryset,year,month)
               salary_data['table']=return_data['rows']
               salary_data['return_data']=return_data['return_data']
            return salary_data
def employees_to_close(post_array,no_of_employees,year,month):
      employees=[]
      for x in range(1,no_of_employees+1):
               if 'closing['+str(x)+']' in  post_array:
                  employees.append(post_array['employee_no['+str(x)+']'])
      queryset = Employee.objects.select_related().filter(employee_no__in=employees).all()
      save_salary(queryset,year,month)
def recalculate_salary(queryset,year,month):
    employees=[x  for x in queryset]
    SavedSalary.objects.filter(employee_no__in=employees).delete()
    save_salary(queryset,year,month)
    
      

class StatutoryReportView(LoginRequiredMixin,ListView):
    form_class = StatutoryReportForm
    template_name = 'nssf_nhif_report.html'
    def get_initial(self):
        initial_base = {}
        initial_base['year']=(datetime.datetime.now().year ,self.request.GET.get('year'))[self.request.GET.get('year') is not None]
        initial_base['month']=(datetime.datetime.now().month,self.request.GET.get('month')) [self.request.GET.get('month') is not None]
        return initial_base

    def get_queryset(self):
        year = self.request.GET.get('year')
        month = self.request.GET.get('month')
        if year and month:
            queryset =Employee.objects.filter(Q(date_of_leaving__isnull=True) | Q(date_of_leaving__range=[period_dates(year, month)['from_date'],period_dates(year, month)['to_date']])| Q(date_of_leaving__gte=period_dates(year, month)['from_date'])).all()
        else:
            queryset = Employee.objects.none()
        form = self.form_class(initial=(self.get_initial()))
        statutories_report_data = {}
        statutories_report_data['form'] = form
        casual_queryset=''
        if queryset:
            return_array=get_statutory_report(year,month,queryset,casual_queryset)
            statutories_report_data['nhif_table'] = return_array['nhif_data']
            statutories_report_data['nhif_total'] = return_array['nhif_total']
            statutories_report_data['nssf_table'] = return_array['nssf_data']
            statutories_report_data['total_income'] = return_array['total_income']
            statutories_report_data['nssf_total_member'] =return_array['nssf_total_member']
            statutories_report_data['nssf_total_employer'] =return_array['nssf_total_employer']
            statutories_report_data['nssf_total_records'] = len(return_array['nssf_data'])
            statutories_report_data['nssf_grand_total'] = Decimal(return_array['nssf_total_employer']) +  Decimal(return_array['nssf_total_member'])
        if Company.get_company_details():
            statutories_report_data['company_name'] = Company.get_company_details()['name']
            statutories_report_data['company_code'] = Company.get_company_details()['nhif_no']
            statutories_report_data['company_pin'] = Company.get_company_details()['pin_no']
            statutories_report_data['company_nssf_no'] = Company.get_company_details()['nssf_no']
        else:
            statutories_report_data['company_name'] = 'Update Company Details'
            statutories_report_data['company_code'] = 'Update Company Details'
            statutories_report_data['company_pin'] = 'Update Company Details'
            statutories_report_data['company_nssf_no'] = 'Update Company Details'
        statutories_report_data['contribution_month'] = month
        statutories_report_data['contribution_year'] = year
        return statutories_report_data
class ItaxReportView(LoginRequiredMixin,ListView):
    form_class = ItaxReportForm
    template_name = 'itax_report.html'
    def get_initial(self):
        initial_base = {}
        initial_base['year']=(datetime.datetime.now().year ,self.request.GET.get('year'))[self.request.GET.get('year') is not None]
        initial_base['month']=(datetime.datetime.now().month,self.request.GET.get('month')) [self.request.GET.get('month') is not None]
        return initial_base
    def get_queryset(self):
        year = self.request.GET.get('year')
        month = self.request.GET.get('month')
        itax_report_data={}
        form = self.form_class(initial=(self.get_initial()))
        itax_report_data['form'] = form
        if year and month:
            period=period_dates(year,month)
        return_arry={}
        total_paye_amount=0
        if year and month:
            queryset =Employee.objects.filter(Q(date_of_leaving__isnull=True) | Q(date_of_leaving__range=[period_dates(year, month)['from_date'],period_dates(year, month)['to_date']])| Q(date_of_leaving__gte=period_dates(year, month)['from_date'])).all()
        else:
            queryset = Employee.objects.none()
        casual_queryset=''
        salary_data=get_statutory_report(year,month,queryset,casual_queryset)
        for key ,values in salary_data['permanent_salary_data'].items():
            total_paye_amount+=values['paye_amount']
            if key not in return_arry:
                temp_other_all_amt =-Decimal(values['absent_amount']) #+ Decimal(values['notice_pay_amount']) - Decimal(values['notice_recovery_amount']) + Decimal(values['severance_amount']) + Decimal(values['directors_fee'])
                temp_gross_not_rounded = Decimal(values['basic_salary']) + Decimal(values['housing_amount']) + Decimal(temp_other_all_amt)
                temp_rounding=Decimal(temp_gross_not_rounded) - Decimal(round_half_up(temp_gross_not_rounded,0))
                return_arry[str(key)+'p']={
                'pin_no':values['pin_no'],
                'employee_name':values['employee_name'],
                'type_of_employee':'Primary Employee',
                'basic_salary':values['basic_salary'],
                'housing_amount':values['housing_amount'],
                'directors_fee':0,#values['directors_fee'],
                'leave_encashed_amount':0, #values['leave_encashed_amount'],
                'over_time_allowance':0,
                'other_allowance':0 + (temp_other_all_amt-temp_rounding),
                'vehicle_benefit':0,
                'other_benefit_amount':0,
                'house_quota':0,
                'nssf_amount':Decimal(values['nssf_amount']),
                'rent_recovered':(values['basic_salary']*(values['house_allowance_rate']/100)),
                'permissible_limit':'',
                'mortgage_interest':0,
                'paye_relief':values['relief_amount'],
                'paye_amount':values['paye_amount'],
                'insurance_relief':values['insurance_relief'],
                }
        itax_report_data['table']=return_arry
        itax_report_data['paye_total']=total_paye_amount
        return itax_report_data

class EmployeePaySlipView(LoginRequiredMixin,ListView):
        form_class=PayslipForm
        template_name ='payslips/employee_pay_slip_form.html'
        def get(self, request,**kwargs):
                form = self.form_class(initial=self.get_initial())
                return render(request,self.template_name, {'form': form})
        def get_initial(self):
                initial_base={}
                initial_base['year']=(datetime.datetime.now().year ,self.request.GET.get('year'))[self.request.GET.get('year') is not None]
                initial_base['month']=(datetime.datetime.now().month,self.request.GET.get('month')) [self.request.GET.get('month') is not None]
                return initial_base
            
def get_print_preview(request):
    form=PayslipForm()
    template_name ='payslips/employee_pay_slip_form.html'
    context = {"form": form}
    if request.POST:

application/salaryreports/templates/itax_report.html
{% extends 'layouts/base.html' %}
{% load humanize %}
{% block content %}
<script>
function exportCSV(){
    $(".exportTbl").tableToCSV();
}
function toggleClass(el, className) {
    if (el.className.indexOf(className) >= 0) {
        el.className = el.className.replace(className,"");
    }
    else {
        el.className  += className;
    }
}
function ShowHighlighted(cb){
	if(cb.checked){
        $("#tbody").find("tr").hide();
        $("#tbody").find(".selected").show();
	}
	else{
	    $("#tbody").find("tr").show();
	}
}
</script>
<style>
    .selected
    {
        background-color: #ff8;
    }
</style>
<div class="" style="width: 600px;padding-top: 0.2cm;">
    <form action="" method="GET" id="itax-report" class="deptsForm">
    {% csrf_token %}
    {{ form.errors }}
    <table id="form" class="table table-striped table-bordered table-hover table-minimal table-scroll">
        <tr class="info">
            <td class="text-center" colspan="6">
                <h5>Itax Benefit Report</h5>
            </td>
        </tr>
        <tr>
            {% for field in object_list.form %}
            <td><strong>{{ field.label }}:</strong> {{field}}</td>
            {% endfor %}
            </tr>
        </tr>
        <tr class="info">
            <td class="text-left tr-btn"  colspan="6">
                <input  class="btn btn-success btn-form"  type="submit" value="Submit" />
                {% if object_list.table %}
                <input  class="btn btn-info btn-form"  type="submit" onclick="exportCSV()" value="Export" />
                <a href="{% url 'salaryreports:itax-report' %}"  class="btn btn-danger btn-form">Cancel</a>
                
            </td>
        </tr>
        <tr>
            <td colspan="6" class="text-center bg-warning">
                <label for="highlightcb"><input id="highlightcb" type="checkbox" onclick="ShowHighlighted(this);" class="auth-ro-allow" style="width: unset ! important;">Highlighted Only</label>

            </td>
        </tr>
        {%endif%}
        </table>
    </form>
</div>
<div style="width: 3250px;">
    {% if object_list.table %}
    <table class="table table-bordered table-minimal exportTbl" id="detail-table">
        <caption style="display:none;">ITax Report-{{object_list.form.year.value}}-{{object_list.form.month.value}} </caption>
        <thead >
        <tr class="info noExport">
            <th>SI</th>
            <th>PIN of Employee</th>
            <th>Name Employee</th>
            <th>Residential Status</th>
            <th>Type of Employee</th>
            <th>Basic Salary</th>
            <th>Housing Allowance</th>
            <th>Transport Allowance</th>
            <th>Leave Pay</th>
            <th>Over Time Allowance</th>
            <th>Director's Fee</th>
            <th>Lump Sum Payment</th>
            <th>Other Allowance</th>
            <th>Total Cash Pay</th>
            <th>Value of Car Benefit</th>
            <th>Other Non Cash Benefits</th>
            <th>Total Non Cash Pay</th>
            <th></th>
            <th>Type of Housing</th>
            <th>House Quota</th>
            <th>Computed Rent of House</th>
            <th>Rent Recovered </br> From Employee</th>
            <th>Net Value of Housing</th>
            <th>Total Gross Pay</th>
            <th>30% of Cash Pay</th>
            <th>Actual Contribution</th>

            <th>Permissible Limit</th>
            <th>Mortgage Interest</th>
            <th>Deposit on Home</th>
            <th>Amount of Benefit</th>
            <th>Taxable Pay</th>
            <th>Tax Payable</th>
            <th>Monthly Personal Relief</th>
            <th>Amount of Insurance Relief</th>
            <th>PAYE Tax</th>
            <th>Self Assessed PAYE Tax</th>
        </tr>
        </thead>
        <tbody id="tbody">
        {% for key,row in object_list.table.items %}
        <tr onclick="toggleClass(this,'selected');">
            <td class="noExport">{{forloop.counter}}</td>
            <td class="text-left">{{row.pin_no}}</td>
            <td class="text-left" style="white-space: nowrap">{{row.employee_name}}</td>
            <td style="white-space: nowrap">Resident</td>
            <td class="text-left" style="white-space: nowrap">{{row.type_of_employee}}</td>
            <td class="text-right">{{row.basic_salary}}</td>
            <td class="text-right">{{row.housing_amount}}</td>
            <td class="text-right">0</td>
            <td class="text-right">{{row.leave_encashed_amount|floatformat:2|intcomma }}</td>
            <td class="text-right">{{row.over_time_allowance|floatformat:2|intcomma}}</td>
            <td class="text-right">{{row.directors_fee|floatformat:2|intcomma}}</td>
            <td class="text-right">0</td>
            <td class="text-right">{{row.other_allowance|floatformat:2|intcomma}}</td>
            <td class="text-right"></td>
            <td class="text-right">{{row.vehicle_benefit|floatformat:2|intcomma}}</td>
            <td class="text-right">{{row.other_benefit_amount|floatformat:2|intcomma}}</td>
            <td></td>
            <td class="text-right">{%if row.house_quota == 0 %}0{%else%}{%endif%}</td>
            <td class="text-right" style="white-space: nowrap">{%if row.house_quota > 0 %}Employer's Owned House{%else%}Benefit not given{%endif%}</td>
            <td class="text-right">{%if row.house_quota > 0 %}{{row.house_quota|floatformat:2|intcomma}}{%else%}{%endif%}</td>
            <td></td>
            <td class="text-right">{{row.rent_recovered|floatformat:2|intcomma}}</td>
            <td></td>
            <td></td>
            <td></td>
            <td class="text-right">{{row.nssf_amount|floatformat:2|intcomma}} </td>
            <td class="text-right">{{row.permissible_limit}}</td>
            <td class="text-right">{{row.mortgage_interest}}</td>
            <td>0</td>
            <td></td>
            <td></td>
            <td></td>
            <td class="text-right">{{row.paye_relief|floatformat:2|intcomma}}</td>
            <td class="text-right">{{row.insurance_relief|floatformat:2|intcomma}}</td>
            <td class="text-right"></td>
            <td class="text-right">{{row.paye_amount|floatformat:2|intcomma}}</td>
        </tr>
        {%endfor%}
        </tbody>
        <tfoot>
            <tr class="info noExport" style="font-weight: bold;">
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>Totals</td>
                <td class="text-right">{{object_list.paye_total|floatformat:2|intcomma}}</td>
            </tr>


        </tfoot>
    </table>
    {%endif%}

</div>



{%endblock%}

application/salaryreports/templates/monthly_salary_report.html
{% extends 'layouts/base.html' %}
{% load static  %}
{% load humanize %}
{% load custom_filters %}
{% block content %}

<script>
    function exportCSV(){
    	$(".exportTbl").tableToCSV();
    }
    function toggleClass(el, className) {
        if (el.className.indexOf(className) >= 0) {
            el.className = el.className.replace(className,"");
        }
        else {
            el.className  += className;
        }
    }
    function ShowHighlighted(cb){
        if(cb.checked){
        $("#tbody").find("tr").hide();
        $("#tbody").find(".selected").show();
        }
        else{
        $("#tbody").find("tr").show();
        }
    }
    $(function(){
        $('#selectall').on('change', function(){
        $('.selectemp').prop('checked',this.checked);
        });
    });
    </script>
     <style  TYPE="text/css" scoped>

        @page{
            size:auto;
            margin:10mm 5mm;
        }
        @media print {
            .hide-on-print {display:none;}
            input[type=text] {
                box-shadow: none;
                border: none;
                line-height: initial;
            }
            body
            {
                    margin: 0px;
            }
    }


    #detail-table > tbody >tr > td{
        padding: 2px 0px 2px 4px !important;
    }
    .selected
    {
        background-color: #bbb;
    }
    </style>
<div class="" style="width: 700px;padding-right: 25px;z-index:-2;margin: 0 auto !important;">
    <form action="" method="GET" id="monthly-report" class="deptsForm">
    {% csrf_token %}
    {{ form.errors }}
    <table id="form" class="table table-striped table-bordered table-hover table-minimal table-scroll">
        <tr class="info">
            <td class="text-center" colspan="6">
                <h5>Monthly Salary Report</h5>
            </td>
        </tr>
        <tr>
            {% for field in object_list.form %}
            <td><strong>{{ field.label }}:</strong> {{field}}</td>
            {% endfor %}
            </tr>
        </tr>
        <tr class="info">
            <td class="text-left tr-btn"  colspan="6">
                <input  class="btn btn-success btn-form hide-on-print"  type="submit" value="Submit" />
                {% if object_list.table %}
                <button type="submit" class="btn btn-info btn-form hide-on-print" value="1" name="close" >Close</button>
                <button type="submit" class="btn btn-info" value="1" style="padding: 3px 6px;" name="update" >Re-Calculate</button>
                <input  class="btn btn-info btn-form"  type="submit" onclick="exportCSV()" value="Export" />
                <a href="{% url 'salaryreports:monthly-salary-report' %}"  class="btn btn-danger btn-form hide-on-print">Cancel</a>

            </td>
        </tr>
        {%endif%}
        </table>
</div>
<div class="1500px;">
    {% if object_list.table %}
    <table class="table table-bordered table-minimal exportTbl" id="detail-table">
        <caption style="display:none;">Monthly Salary Report-{{object_list.form.year.value}}-{{object_list.form.month.value}} </caption>
        <thead class="info">
        <tr>
            <td class="hidewhensummary" style="font-weight:bold; vertical-align:bottom;">Si</td>   
            <td class="hidewhensummary noExport hide-on-print" style="font-weight:bold; vertical-align:bottom;">Close</br>
                <input class = "auth-ro-allow hide-on-print" id='selectall' type="checkbox" title= "Check the Red Highlights !!!!">
              </td>       
            <td class="hidewhensummary" style="font-weight:bold; vertical-align:bottom;">Emp No</td>            
            <td style="font-weight:bold; vertical-align:bottom;">Name</td>
            <td class="hidewhensummary" style="font-weight:bold; vertical-align:bottom;">National ID</td>            
            <td class="hidewhensummary" style="font-weight:bold; vertical-align:bottom;">Daily Rate</td>
            {% for key,names in object_list.return_data.value_keys.items %}
                <td style="font-weight:bold; vertical-align:bottom;" class="{{key}}">{{names}}</td>
            {%endfor%}
        </tr>
        </thead>
        <tbody id="tbody">
            {% for key,row in  object_list.table.items %}           
            <tr>
                <td>{{forloop.counter}}</td>
                <td class="text-center noExport hide-on-print" style="white-space: nowrap;">{% if row.closed %}closed {%else%} <input type="checkbox" class="selectemp" name="closing[{{forloop.counter}}]" title= "Check the Red Highlights !!!!"> {%endif%}</td>
                <td class="text-left noExport" style="white-space: nowrap;display:none;"><input type="text"  name="employee_no[{{forloop.counter}}]" value="{{row.employee_no}}"></td>
                <td class="text-left" style="white-space: nowrap">{{row.employee_no}}</td>
                <td class="text-left" style="white-space: nowrap">{{row.employee_name}}</td>
                <td class="text-left hidewhentotal" style="white-space: nowrap">{{row.national_id}}</td>
                <td class="text-right" style="white-space: nowrap">{{row.gross_daily_rate|intcomma}}</td>                
                {% for key,name in object_list.return_data.value_keys.items %}
                <td class="text-right">{{row|dict_lookup:key|intcomma}}</td>
                {%endfor%}
           </tr>
          {%endfor%}
        </tbody>
    </table>
    {%endif%}

   
</form>
</div>
{% endblock %}