application/application/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from dbmaster.views import HomeView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', TemplateView.as_view(template_name="registration/login.html"),name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('employees/',include('employees.urls')),   
    path('attendance/',include('attendance.urls')),   
    path('salaryreports/',include('salaryreports.urls')),
    path('',include('dbmaster.urls')),  
]

application/dbmaster/urls.py
from django.urls import include, path
from . import  views
from dbmaster.views import HomeView

app_name="dbmaster"
urlpatterns = [
     path('',HomeView.as_view(),name='home'),
         
]

application/employees/urls.py
from django.urls import include, path
from employees.models import get_employees

from employees.views import (EmployeeCreateView, EmployeeUpdateView, get_form,
                             navigate_form)

from . import views

app_name="employees"
urlpatterns = [
     path('employee-create/',EmployeeCreateView.as_view(),name='employee-create'),
     path('<int:pk>/update',EmployeeUpdateView.as_view(),name='employee-details'),
     path('nav-employees/',views.navigate_form,name='nav-employees'),
     path('get_form/',views.get_form, name='get_form'),
     path('json/emps-autocomplete/',get_employees, name='emps-autocomplete'),    
    
]

application/employees/models.py
from django.db import models

import datetime
import os
import json
from decimal import Decimal

from dbmaster.models import (WorkingHour,get_post_array)
from django.core.validators import FileExtensionValidator
from django.db import models
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse

from django.urls import reverse

class Employee(models.Model):
      employee_no=models.AutoField(primary_key=True)
      first_name=models.CharField(max_length=100) 
      other_name=models.CharField(max_length=100)      
      national_id=models.CharField(max_length=11)      
      date_of_joining=models.DateField()
      date_of_leaving=models.DateField(blank=True,null=True)
      is_active=models.BooleanField(blank=True,null=True,default=True)     
      work_hours_code=models.ForeignKey(WorkingHour,on_delete=models.PROTECT)
      basic_salary=models.DecimalField(max_digits=12,decimal_places=2,blank=True,null=True)
      house_allowance_rate=models.DecimalField(max_digits=12,decimal_places=2,blank=True,null=True)
      housing_levy_rate=models.DecimalField(max_digits=12,decimal_places=2,blank=True,null=True)
      pin_no=models.CharField(max_length=11,blank=True,null=True)
      nssf_no=models.CharField(max_length=11,blank=True,null=True)
      nhif_no=models.CharField(max_length=11,blank=True,null=True)
     


      class Meta:
            verbose_name_plural = "Employee"
            
            
      def get_absolute_url(self):
          return reverse('employees:employee-details',kwargs={'pk': self.pk})
    
    

def get_employees(request):         
      query = request.GET.get("term", "")
      emps = Employee.objects.filter(Q(employee_no__icontains=query)|Q(first_name__icontains=query)|Q(other_name__icontains=query),is_active=1).all()
      results = []
      for emp in emps:
            new_row={}
            new_row['label'] = str(emp.employee_no) + ' - '+emp.first_name +' '+emp.other_name
            new_row['value'] = emp.employee_no
            results.append(new_row)
            data = json.dumps(results)
      mimetype = "application/json"
      return HttpResponse(data, mimetype)

def get_emp_details(request):
      data = {'employee_name': [],'basic_salary':[]}
      q = request.GET.get("code", "")
      emp_details = Employee.objects.filter(employee_no=q)
      for emp in emp_details:
            data['employee_name'].append(emp.first_name +' '+emp.other_name)
            data['basic_salary'].append(emp.basic_salary)
      return JsonResponse(data, safe = True)

application/employees/forms.py
from dbmaster.models import WorkingHour
from django import forms
from employees.models import Employee
from django.forms.models import inlineformset_factory

class EmployeeCreateForm(forms.ModelForm):
        class Meta:
            model =Employee
            fields='__all__'      
        employee_no=forms.ModelChoiceField(
                    queryset = Employee.objects.all(),
                    widget=forms.TextInput(attrs={
                    'size':6,
                    'class':"form-control",
                    'placeholder':"Emp No",
                    'style':'text-align:center;'
            }),required=False)
        first_name= forms.CharField(widget=forms.TextInput(attrs={'autocomplete':'off',
                    'class':"form-control",
                    'placeholder':"Enter First Name",                                                                 
                }),required=False)
        
        other_name= forms.CharField(widget=forms.TextInput(attrs={'autocomplete':'off',
                    'class':"form-control",
                    'placeholder':"Enter Other Names ",                                                                 
                }),required=False)
        date_of_joining=forms.DateField(widget=forms.TextInput(attrs={
                    'id':'date_of_joining',
                    'value':'',
                    'autocomplete':'off',
                    'class':"form-control",
                    'type':'date',
                }))
        date_of_leaving=forms.DateField(widget=forms.TextInput(attrs={
                    'id':'date_of_leaving',
                    'value':'',
                    'class':"form-control",
                    'autocomplete':'off',
                    'type':'date',
                }),required=False)      
        work_hours_code=forms.ModelChoiceField(
                queryset=WorkingHour.objects.all().order_by('id'),
                empty_label='Select Working Hours',
                required=True,
            )
        basic_salary=forms.DecimalField(
                widget=forms.TextInput(attrs={
                    'id':'id_basic_salary',
                    'value':'',
                    'class':"form-control",                
                    'autocomplete':'off',
                }))
        house_allowance_rate=forms.DecimalField(
                widget=forms.TextInput(attrs={                   
                    'value':'',
                    'class':"form-control",                
                    'autocomplete':'off',
                }))
        housing_levy_rate=forms.DecimalField(
                widget=forms.TextInput(attrs={                   
                    'value':'',
                    'class':"form-control",                
                    'autocomplete':'off',
                }))
        national_id=forms.CharField(widget=forms.TextInput(attrs={'autocomplete':'off',
                    'class':"form-control",
                    'placeholder':"Enter National ID",                                                                 
                }))
        pin_no=forms.CharField(widget=forms.TextInput(attrs={'autocomplete':'off',
                    'class':"form-control",
                    'placeholder':"Enter PIN NO",                                                                 
                }))
        nssf_no=forms.CharField(widget=forms.TextInput(attrs={'autocomplete':'off',
                    'class':"form-control",
                    'placeholder':"Enter NSSF NO",                                                                 
                }))
        nhif_no=forms.CharField(widget=forms.TextInput(attrs={'autocomplete':'off',
                    'class':"form-control",
                    'placeholder':"Enter NHIF NO",                                                                 
                }))
        

class EmployeeUpdateForm(forms.ModelForm):
    class Meta:
        model =Employee
        fields='__all__'

    employee_no=forms.ModelChoiceField(
                queryset = Employee.objects.all(),
                widget=forms.TextInput(attrs={
                'size':6,
                'class':"form-control",
                'placeholder':"Emp No",
                'style':'text-align:center;'
        }),required=False)
      
      
    first_name= forms.CharField(widget=forms.TextInput(attrs={'autocomplete':'off',
                    'class':"form-control",
                    'placeholder':"Enter First Name",                                                                 
                }),required=False)
        
    other_name= forms.CharField(widget=forms.TextInput(attrs={'autocomplete':'off',
                    'class':"form-control",
                    'placeholder':"Enter Other Names ",                                                                 
                }),required=False)
    date_of_joining=forms.DateField(widget=forms.TextInput(attrs={
            'id':'date_of_joining',
            'value':'',
            'autocomplete':'off',
            'class':"form-control",
            'type':'date',
        }))
    date_of_leaving=forms.DateField(widget=forms.TextInput(attrs={
            'id':'date_of_leaving',
            'value':'',
            'class':"form-control",
            'autocomplete':'off',
            'type':'date',
        }),required=False)      
    work_hours_code=forms.ModelChoiceField(
        queryset=WorkingHour.objects.all().order_by('id'),
        empty_label='Select Working Hours',
        required=True,
    )
    basic_salary=forms.DecimalField(
        widget=forms.TextInput(attrs={
            'id':'id_basic_salary',
            'value':'',
            'class':"form-control",                
            'autocomplete':'off',
        }))
    house_allowance_rate=forms.DecimalField(
                widget=forms.TextInput(attrs={                   
                    'value':'',
                    'class':"form-control",                
                    'autocomplete':'off',
                }))
    housing_levy_rate=forms.DecimalField(
                widget=forms.TextInput(attrs={                   
                    'value':'',
                    'class':"form-control",                
                    'autocomplete':'off',
                }))
    national_id=forms.CharField(widget=forms.TextInput(attrs={'autocomplete':'off',
            'class':"form-control",
            'placeholder':"Enter National ID",                                                                 
        }))
    pin_no=forms.CharField(widget=forms.TextInput(attrs={'autocomplete':'off',
            'class':"form-control",
            'placeholder':"Enter PIN NO",                                                                 
        }))
    nssf_no=forms.CharField(widget=forms.TextInput(attrs={'autocomplete':'off',
            'class':"form-control",
            'placeholder':"Enter NSSF NO",                                                                 
        }))
    nhif_no=forms.CharField(widget=forms.TextInput(attrs={'autocomplete':'off',
            'class':"form-control",
            'placeholder':"Enter NHIF NO",                                                                 
        }))
      

application/employees/views.py
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.contrib.messages.views import SuccessMessageMixin
from django.forms.models import inlineformset_factory
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from employees.forms import EmployeeCreateForm,EmployeeUpdateForm
from employees.models import Employee
from dbmaster.models import navigate_model,get_post_array


# Create your views here.
class EmployeeCreateView(LoginRequiredMixin,SuccessMessageMixin,CreateView):
    template_name='employee.html'
    form_class=EmployeeCreateForm
    success_message="Employee Added"
    
    def get_success_url(self):
             return reverse("employees:employee-details",kwargs={'pk':self.object.employee_no})
         
class EmployeeUpdateView(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
      model=Employee
      template_name='employee_detail.html'
      success_message="Updated"
      form_class=EmployeeUpdateForm
      
      
def get_form(request):
      if request.POST:
            emp_id=get_post_array(request.POST.items(), dict())['employee_no']
            return HttpResponseRedirect(reverse("employees:employee-details",kwargs={'pk':emp_id}))
def navigate_form(request):
      print(get_post_array(request.POST.items(),dict()))
      if request.POST:
            nav_btn_data=get_post_array(request.POST.items(),dict())
          
            if nav_btn_data['nav-button']=='first':
                  query=Employee.objects.order_by('employee_no').first()
                  if query:
                        return HttpResponseRedirect(reverse("employees:employee-details",kwargs={'pk':query.employee_no}))
                  else:
                        return HttpResponseRedirect(reverse("employees:employee-create"))

            elif nav_btn_data['nav-button'] =='forward':
                  if nav_btn_data['employee_no']:
                              query=Employee.objects.filter(employee_no__gt=nav_btn_data['employee_no']).order_by('employee_no').first()
                              if query:
                                    return HttpResponseRedirect(reverse("employees:employee-details",kwargs={'pk':query.employee_no}))
                              else:
                                    query=Employee.objects.order_by('employee_no').first()
                                    return HttpResponseRedirect(reverse("employees:employee-details",kwargs={'pk':query.employee_no}))
                  else :
                        query=Employee.objects.order_by('employee_no').first()
                        if query:
                                   return HttpResponseRedirect(reverse("employees:employee-details",kwargs={'pk':query.employee_no}))
                        else:
                                   return HttpResponseRedirect(reverse("employees:employee-create"))

            elif nav_btn_data['nav-button'] =='backward':
                  if nav_btn_data['employee_no']:
                        query=Employee.objects.filter(employee_no__lt=nav_btn_data['employee_no']).order_by('employee_no').last()
                        if query:
                              return HttpResponseRedirect(reverse("employees:employee-details",kwargs={'pk':query.employee_no}))

                        else:
                              query=Employee.objects.order_by('employee_no').last()
                              return HttpResponseRedirect(reverse("employees:employee-details",kwargs={'pk':query.employee_no}))

                  else:
                        query=Employee.objects.order_by('employee_no').last()
                        if query:
                              return HttpResponseRedirect(reverse("employees:employee-details",kwargs={'pk':query.employee_no}))

                        else:
                               return HttpResponseRedirect(reverse("employees:employee-create"))
            elif  nav_btn_data['nav-button']=='last':
                  query=Employee.objects.order_by('employee_no').last()
                  if query:
                         return HttpResponseRedirect(reverse("employees:employee-details",kwargs={'pk':query.employee_no}))
                  else:
                         return HttpResponseRedirect(reverse("employees:employee-create"))
                   

application/employees/templates/employee.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
<script type="text/javascript">
    $(document).ready(function() {
       $("button[name='nav-button']").click(function() {
        $('#employeeform').attr('action',"{% url 'employees:nav-employees'%}").submit();
        });
    });
    $( function() {
          $("#id_employee_no").autocomplete({
            source:"{% url 'employees:emps-autocomplete' %}",
            autoFocus: true,
            select: function(event, ui) {
                    $(event.target).val(ui.item.value);
                    $('#employeeform').attr('action',"{% url 'employees:get_form'%}").submit();
                    return false;
            }
          });
    });
</script> 


<form  action="" enctype="multipart/form-data" method="POST" id="employeeform" >
    {% csrf_token %}
    {{form.media}}
    <div class="pd-50 pd-sm-60 bg-white wd-xl-70p" style="margin: 0 auto;">
       
        <div class="row row-sm">
            <div class="col-lg-4 mg-t-20 mg-lg-t-0 text-left">
                <div class="btn-group" role="group" aria-label="Basic example">
                    <button type="submit" class="btn btn" name="nav-button" value="first" formnovalidate>
                        <span class="fa fa-fast-backward"></span></button>
                    <button type="submit" class="btn btn" accesskey="p" name="nav-button" value="backward" formnovalidate>
                        <span class="fa fa-step-backward"></span></button>
                </div>
              </div><!-- col-2 -->
              <div class="col-lg-4 mg-t-20 mg-lg-t-0 text-center">
                <h4 class="text-center" style="font-weight: bolder;">Employee Form</h4>
              </div>
              <div class="col-lg-4 mg-t-20 mg-lg-t-0 text-right">
                <div class="btn-group" role="group" aria-label="Basic example">
                    <button type="submit" class="btn btn" accesskey="n" name="nav-button" value="forward" formnovalidate>
                        <span class="fa fa-step-forward"></span></button>
                    <button type="submit" class="btn btn" name="nav-button" value="last" formnovalidate>
                        <span class="fa fa-fast-forward"></span></button>
                </div>
              </div>

        </div>
    </br>
        <div class="row row-xs align-items-center mg-b-20">
                <div class="col-md-2">
                    <label class="form-label mg-b-0">Emp No</label>
                </div><!-- col -->
                <div class="col-md-2">
                   {{form.employee_no}}
                </div><!-- col -->
                <div class="col-md-4 mg-t-5 mg-md-t-0">
                    {{form.first_name}}
                </div><!-- col -->   
                <div class="col-md-4 mg-t-5 mg-md-t-0">
                    {{form.other_name}}
                </div><!-- col -->
        </div><!-- row -->
        <div class="row row-xs align-items-center mg-b-20">
                <div class="col-md-2">
                    <label class="form-label mg-b-0">ID No</label>
                </div><!-- col -->
                <div class="col-md-4 mg-t-5 mg-md-t-0">
                    {{form.national_id}}
                </div><!-- col -->

                <div class="col-md-2">
                    <label class="form-label mg-b-0">PIN No</label>
                </div><!-- col -->
                <div class="col-md-4 mg-t-5 mg-md-t-0">
                    {{form.pin_no}}
                </div><!-- col -->

        </div><!-- row -->
        <div class="row row-xs align-items-center mg-b-20">
            <div class="col-md-2">
                <label class="form-label mg-b-0">NSSF  No</label>
            </div><!-- col -->
            <div class="col-md-4 mg-t-5 mg-md-t-0">
                {{form.nssf_no}}
            </div><!-- col -->

            <div class="col-md-2">
                <label class="form-label mg-b-0">NHIF No</label>
            </div><!-- col -->
            <div class="col-md-4 mg-t-5 mg-md-t-0">
                {{form.nhif_no}}
            </div><!-- col -->

        </div><!-- row -->
        <div class="row row-xs align-items-center mg-b-20">
            <div class="col-md-2">
                <label class="form-label mg-b-0">Date Of Joining</label>
            </div><!-- col -->
            <div class="col-md-4 mg-t-5 mg-md-t-0">
                {{form.date_of_joining}}
            </div><!-- col -->

            <div class="col-md-2">
                <label class="form-label mg-b-0">Date Of Leaving</label>
            </div><!-- col -->
            <div class="col-md-4 mg-t-5 mg-md-t-0">
              {{form.date_of_leaving}}
            </div><!-- col -->
        </div><!-- row -->
        <div class="row row-xs align-items-center mg-b-20">
            <div class="col-md-2">
                <label class="form-label mg-b-0">Working Hours</label>
            </div><!-- col -->
            <div class="col-md-10 mg-t-5 mg-md-t-0">
               {{form.work_hours_code}}
            </div><!-- col -->           
        </div><!-- row -->
        <div class="row row-xs align-items-center mg-b-20">
            <div class="col-md-2">
                <label class="form-label mg-b-0">Basic Salary</label>
            </div><!-- col -->
            <div class="col-md-3 mg-t-5 mg-md-t-0">
                {{form.basic_salary}}
            </div><!-- col -->
            <div class="col-md-3">
                <label class="form-label mg-b-0">House Allowance Rate</label>
            </div><!-- col -->
            <div class="col-md-4 mg-t-5 mg-md-t-0">
                {{form.house_allowance_rate}}
            </div><!-- col -->
        </div><!-- row -->
        <div class="row row-xs align-items-center mg-b-20">
            <div class="col-md-2">
                <label class="form-label mg-b-0">Housing Levy Rate</label>
            </div><!-- col -->
            <div class="col-md-3 mg-t-5 mg-md-t-0">
                {{form.housing_levy_rate}}
            </div><!-- col -->
            <div class="col-md-3">
              
            </div><!-- col -->
            <div class="col-md-4 mg-t-5 mg-md-t-0">
             
            </div><!-- col -->
        </div><!-- row -->
        <input  class="btn btn-az-primary pd-x-30 mg-r-5"  type="submit" value="Register"/>
    </div>
</form>

{%endblock%}

application/employees/templates/employee_detail.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
<script type="text/javascript">
    $(document).ready(function() {
       $("button[name='nav-button']").click(function() {
        $('#employeeform').attr('action',"{% url 'employees:nav-employees'%}").submit();
        });
    });
</script> 
<form enctype="multipart/form-data" method="POST" id="employeeform" >
    {% csrf_token %}
    {{form.media}}
    <div class="pd-50 pd-sm-60 bg-white wd-xl-70p" style="margin: 0 auto;">
        <div class="row row-sm">

            <div class="col-lg-4 mg-t-20 mg-lg-t-0 text-left">
                <div class="btn-group" role="group" aria-label="Basic example">
                    <button type="submit" class="btn btn" name="nav-button" value="first" formnovalidate>
                        <span class="fa fa-fast-backward"></span></button>
                    <button type="submit" class="btn btn" accesskey="p" name="nav-button" value="backward" formnovalidate>
                        <span class="fa fa-step-backward"></span></button>
                </div>
              </div><!-- col-2 -->
              <div class="col-lg-4 mg-t-20 mg-lg-t-0 text-center">
                <h4 class="text-center" style="font-weight: bolder;">Employee Form</h4>
              </div>
              <div class="col-lg-4 mg-t-20 mg-lg-t-0 text-right">
                <div class="btn-group" role="group" aria-label="Basic example">
                    <button type="submit" class="btn btn" accesskey="n" name="nav-button" value="forward" formnovalidate>
                        <span class="fa fa-step-forward"></span></button>
                    <button type="submit" class="btn btn" name="nav-button" value="last" formnovalidate>
                        <span class="fa fa-fast-forward"></span></button>
                </div>
              </div>

        </div>
        &nbsp;
        <div class="row row-xs align-items-center mg-b-20">
                <div class="col-md-2">
                    <label class="form-label mg-b-0">Emp No</label>
                </div><!-- col -->
                <div class="col-md-2">
                   {{form.employee_no}}
                </div><!-- col -->
                <div class="col-md-4 mg-t-5 mg-md-t-0">
                    {{form.first_name}}
                </div><!-- col -->   
                <div class="col-md-4 mg-t-5 mg-md-t-0">
                    {{form.other_name}}
                </div><!-- col -->

        </div><!-- row -->
        <div class="row row-xs align-items-center mg-b-20">
                <div class="col-md-2">
                    <label class="form-label mg-b-0">ID No</label>
                </div><!-- col -->
                <div class="col-md-4 mg-t-5 mg-md-t-0">
                    {{form.national_id}}
                </div><!-- col -->

                <div class="col-md-2">
                    <label class="form-label mg-b-0">PIN No</label>
                </div><!-- col -->
                <div class="col-md-4 mg-t-5 mg-md-t-0">
                    {{form.pin_no}}
                </div><!-- col -->

        </div><!-- row -->
        <div class="row row-xs align-items-center mg-b-20">
            <div class="col-md-2">
                <label class="form-label mg-b-0">NSSF  No</label>
            </div><!-- col -->
            <div class="col-md-4 mg-t-5 mg-md-t-0">
                {{form.nssf_no}}
            </div><!-- col -->

            <div class="col-md-2">
                <label class="form-label mg-b-0">NHIF No</label>
            </div><!-- col -->
            <div class="col-md-4 mg-t-5 mg-md-t-0">
                {{form.nhif_no}}
            </div><!-- col -->

        </div><!-- row -->
        <div class="row row-xs align-items-center mg-b-20">
            <div class="col-md-2">
                <label class="form-label mg-b-0">Date Of Joining</label>
            </div><!-- col -->
            <div class="col-md-4 mg-t-5 mg-md-t-0">
                {{form.date_of_joining}}
            </div><!-- col -->

            <div class="col-md-2">
                <label class="form-label mg-b-0">Date Of Leaving</label>
            </div><!-- col -->
            <div class="col-md-4 mg-t-5 mg-md-t-0">
              {{form.date_of_leaving}}
            </div><!-- col -->
        </div><!-- row -->
        <div class="row row-xs align-items-center mg-b-20">
            <div class="col-md-2">
                <label class="form-label mg-b-0">Working Hours</label>
            </div><!-- col -->
            <div class="col-md-10 mg-t-5 mg-md-t-0">
               {{form.work_hours_code}}
            </div><!-- col -->           
        </div><!-- row -->
        <div class="row row-xs align-items-center mg-b-20">
            <div class="col-md-2">
                <label class="form-label mg-b-0">Basic Salary</label>
            </div><!-- col -->
            <div class="col-md-3 mg-t-5 mg-md-t-0">
                {{form.basic_salary}}
            </div><!-- col -->
            <div class="col-md-3">
                <label class="form-label mg-b-0">House Allowance Rate</label>
            </div><!-- col -->
            <div class="col-md-4 mg-t-5 mg-md-t-0">
                {{form.house_allowance_rate}}
            </div><!-- col -->
        </div><!-- row -->
        <div class="row row-xs align-items-center mg-b-20">
            <div class="col-md-2">
                <label class="form-label mg-b-0">Housing Levy Rate</label>
            </div><!-- col -->
            <div class="col-md-3 mg-t-5 mg-md-t-0">
                {{form.housing_levy_rate}}
            </div><!-- col -->
            <div class="col-md-3">
              
            </div><!-- col -->
            <div class="col-md-4 mg-t-5 mg-md-t-0">
             
            </div><!-- col -->
        </div><!-- row -->
        <input  class="btn btn-az-primary pd-x-30 mg-r-5"  type="submit" value="Update"/>
        <a href="{% url 'employees:employee-create' %}"  class="btn btn-dark pd-x-30">Cancel</a>

              
    </div>
</form>

{%endblock%}